### PR TITLE
Package refactoring, for consistency with Grails 3 plugins.

### PR DESCRIPTION
**Pull request by donbeave**
Little cleanup in repository.

### CODE REVIEW

**Comment by stokito** [comment]
great, I'll try to review it today, but please ping me if i forget

**Comment by donbeave** [comment]
no problem, I will

**Comment by stokito** [comment]
Hi @donbeave 
I checked your pull request. Thanks for your work, I will merge it manually. Also I commented some parts, please review my comments

**Comment by ctoestreich** [comment]
Are you going to accept these?  Also I have a local copy published to my bintray no as you have not pushed this up to bintray or added this to the main grails plugin bintray as best as I can tell.

**Comment by stokito** [comment]
Hi @ctoestreich  I'm planning to merge it on the next week

**Pull request closed without merging**
