### PR TITLE
Adding ability to externalize config and use string booleans.

### PR DESCRIPTION
**Pull request by ctoestreich**
Also doing cyclomatic complexity cleanup on code

### CODE REVIEW

**Comment by stokito** [comment]
Hi @ctoestreich 
Thanks for your pull request, it's looks cool. Travis Ci says that test are failed https://travis-ci.org/stokito/grails-cookie
Could you check why?
I can do it myself, if you not interested

**Comment by stokito** [comment]
I reverted some small changes:

1. `return` keyword is always explicit to avoid errors during refactorings 
2. `writeCookieToResponse()` doesn't change cookie value, so it should be void 
3. `getDefaultCookiePath(String path = '')` was reverted because this default param value never used.

**Comment by ctoestreich** [comment]
Thanks for adding so quickly.   The changes you made above make sense.  I noticed that the grails required version was bumped to 2.4 > *.  This is not exactly the case.  I tested this with 2.2.1, 2.3.8 and 2.4.0 and all versions of grails > 2.2 were able to use the plugin.  I reverted the required version back to 2.2 to allow broader use of the plugin.  Thanks!

**Comment by stokito** [comment]
Yep, but problem was with running unit tests, they failed in grails 2.2.0

**Pull request merged**
